version: "3.9"

services:
  db:
    container_name: JustEaTime-mongodb
    image: mongo:6.0.5
    restart: always
    ports:
      - 27017:27017
    networks:
      - backend_network

  express:
    container_name: JustEaTime-mongo-express
    image: mongo-express:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
    networks:
      - backend_network

  backend:
    container_name: JustEaTime-backend
    build:
      context: server
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./server:/node/app
      - /node/node_modules
    depends_on:
      - db
    networks:
      - backend_network

  redis:
    container_name: JustEaTime-redis
    image: redis:7.2-rc2-alpine3.18
    restart: always
    depends_on:
      - backend
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - backend_network

  frontend:
    container_name: JustEaTime-frontend
    build:
      context: client
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./client:/node/app
      - /node/node_modules
    depends_on:
      - backend
    networks:
      - frontend_network

  nginx:
    container_name: JustEaTime-nginx
    image: nginx:1.24.0-perl
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - frontend_network
      - backend_network

networks:
  backend_network:
  frontend_network:
