version: "3.7"

services:
  db:
    image: mongo:latest
    restart: always
    volumes:
      - ./db_data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=papo
      - MONGO_INITDB_ROOT_PASSWORD=papo
      - MONGO_INITDB_DATABASE=test
    networks:
      - backend_network

  # Add mongo-express to the docker-compose.yml file
  # This will allow you to view the database in a web browser
  express:
    image: mongo-express:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=papo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=papo
      - ME_CONFIG_MONGODB_SERVER=db
    networks:
      - backend_network

  backend:
    build:
      context: server
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app
    networks:
      - backend_network

  frontend:
    build:
      context: client
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    volumes:
      - ./client:/usr/src/app
    networks:
      - frontend_network
      - backend_network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - frontend_network

networks:
  backend_network:
  frontend_network:
